RAW_DATA="data.csv"
ANNOTATED_DATA="dt_sleep.csv"
BINNED_DATA="dt_binned.csv"
DEFAULT_TIME_WINDOW_LENGTH=10
DEFAULT_VELOCITY_CORRECTION_COEF=0.06
DEFAULT_MIN_TIME_IMMOBILE=300
DEFAULT_SUMMARY_TIME_WINDOW=30*60
DEFAULT_REFERENCE_HOUR=6